// SPDX-License-Identifier: AGPL-3.0-or-later
import type { EffectiveReviewCiConfig } from "../../core/config/forgedock-config.js";
import type { PullRequestMergeGate, PullRequestSnapshot } from "../../core/ports/forge-host.js";
export type PullRequestKind = "delivery" | "promotion" | "deployment";
export type PullRequestCheck = PullRequestMergeGate["requiredChecks"][number];
export interface PullRequestCiAssessment { kind: PullRequestKind; selected: readonly PullRequestCheck[]; pending: readonly PullRequestCheck[]; failed: readonly PullRequestCheck[]; mergeable: boolean; ready: boolean; }
export class PullRequestCiBlockedError extends Error { constructor(readonly assessment: PullRequestCiAssessment, readonly failureAction: EffectiveReviewCiConfig["failureAction"], phase: "before" | "after") { super(formatPullRequestCiBlock(assessment, failureAction, phase)); this.name = "PullRequestCiBlockedError"; } }
export function classifyPullRequest(pr: Pick<PullRequestSnapshot, "headBranch" | "baseBranch">, lanes: { featurePromotionTarget?: string; productionTarget?: string } = {}): PullRequestKind { const integration = lanes.featurePromotionTarget ?? "staging"; const production = lanes.productionTarget ?? "main"; if (pr.headBranch === integration && pr.baseBranch === production) return "deployment"; if (pr.baseBranch === integration || pr.headBranch.startsWith("milestone/")) return "promotion"; return "delivery"; }
export function assessPullRequestCi(pr: Pick<PullRequestSnapshot, "headBranch" | "baseBranch">, gate: PullRequestMergeGate, policy: EffectiveReviewCiConfig, lanes: { featurePromotionTarget?: string; productionTarget?: string } = {}): PullRequestCiAssessment { const kind = classifyPullRequest(pr, lanes); const selectors = (kind === "deployment" ? policy.deploymentChecks : kind === "promotion" ? policy.promotionChecks : policy.deliveryChecks).map((selector) => selector.trim()); const eligible = gate.requiredChecks; const selected = eligible.filter((check) => selectors.some((selector) => checkMatches(selector, check.name))); const missing = selectors.filter((selector) => selector !== "*" && !eligible.some((check) => checkMatches(selector, check.name))).map((name): PullRequestCheck => ({ name, state: "unavailable" })); if (selectors.includes("*") && eligible.length === 0) missing.push({ name: "repository PR checks", state: "unavailable" }); const authoritative = [...selected, ...missing]; const pending = authoritative.filter((check) => check.state === "pending"); const failed = authoritative.filter((check) => check.state !== "passed" && check.state !== "pending"); return { kind, selected: authoritative, pending, failed, mergeable: gate.mergeable, ready: gate.mergeable && !pending.length && !failed.length }; }
export function assertPullRequestCiReady(a: PullRequestCiAssessment, action: EffectiveReviewCiConfig["failureAction"], phase: "before" | "after"): void { if (!a.ready) throw new PullRequestCiBlockedError(a, action, phase); }
export function formatPullRequestCiBlock(a: PullRequestCiAssessment, action: EffectiveReviewCiConfig["failureAction"], phase: "before" | "after"): string { const reasons = [...(!a.mergeable ? ["merge conflict or GitHub mergeability is unresolved"] : []), ...a.pending.map((c) => `${c.name}=pending${c.detailsUrl ? ` (${c.detailsUrl})` : ""}`), ...a.failed.map((c) => `${c.name}=${c.state}${c.detailsUrl ? ` (${c.detailsUrl})` : ""}`)]; const next = action === "auto-fix" ? "ForgeDock auto-fix was enabled but could not safely make the selected checks green. Fix the listed checks on the PR head, then rerun /review-pr." : "Please fix the listed PR CI/mechanical checks on the PR head, then rerun /review-pr. To let ForgeDock attempt bounded repairs, set next.review.ci.failure_action to auto-fix with /forgedock-config."; return `ForgeDock ${a.kind} PR checks are not green ${phase === "before" ? "before independent review" : "after independent review of the exact head"}: ${reasons.join(", ") || "no authoritative passing checks were observed"}. ${next}`; }
function checkMatches(selector: string, name: string): boolean { const pattern = selector.trim().toLowerCase(); const candidate = name.trim().toLowerCase(); if (pattern === "*") return true; const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replaceAll("*", ".*"); return new RegExp(`^${escaped}$`, "i").test(candidate); }
